### PR TITLE
Added type and type_att_info to fix Issue 37

### PR DESCRIPTION
**Pull request by ForceComDeveloper**
Just added type_att_info field as private and type field as public to each element extending sOject_x class.
I tried to add it as public member of the sObject_x class but did not worked

### CODE REVIEW

**Comment by afawcett** [comment]
Thanks for this, while i think the way your initialising the type member has it benefits, i am concerned about Salesforce modifying the behaviour of valueOf, as its not really documented. I understand the desire not to hard code literal text but on balance i think the stability of a literal string or perhaps Class.class.getName() is better. What do you think?

**Comment by ForceComDeveloper** [comment]
MyClass.class.getName() is the same has the hard coded string for
maintenability to me. If the class name change, the code has to change too.
And in this case, the hard coded string is better for performance reason I
think. This is why I use this method. I think it is better for
maintainability. I tried to put it in the base class with public for the
type string and protected attribut for the att_type_info String array
because it works dynamically but it seems the WebService do not take that
and we have to put those attribut in each sub class.
What do you prefer ? We let it this way ? Or we hard code the string ?

**Comment by afawcett** [comment]
I appreciate your motivations, however on balance i think the frequency of such an error occuring is low as its not often such type classes will be created and its a concern of the developer of the library rather than the user of it. Given the possibly fragile nature of the valueOf value returning something else in the future impacting the user of the library, i think on balance i'd go for the string option.

**Comment by afawcett** [comment]
Thanks for this, sorry it dropped off my radar for bit. Thanks for your submission! 👍

**Comment by ForceComDeveloper** [comment]
Bonjour afawcett/apex-toolingapi,
Sebastien Colladon vous a laissé un message sur IQ Elite 
Cliquez ici a.iqelite.com/j/z8pJaH/q10/?hg=BLWDpeq7cT pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=b9fa6f22&email=reply@reply.github.com.&hg=BLWDpeq7cT
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Pull request merged**
